### ISSUE TITLE
RethinkDB Adapter

### ISSUE THREAD

**Issue by thelinuxlich** [grahamjenson/ger#15]
I've started working on a RethinkDB adapter for this great project, it's on my fork:

https://github.com/thelinuxlich/ger/

So far, 44 of 70 tests are passing, I'm lagging behind the latest commit(as of 01/12/2014), but the great challenge is to match the same weight of the jaccard algorithm using SQL, if anyone has suggestions, please come here :)

**Comment by danielbuechele** [comment]
This ESM is still on a feature-branch not merged into master. Is it not finished yet? Or what's the reason for this not being part of master?

**Comment by thelinuxlich** [comment]
hi @danielbuechele , latest driver is here: https://github.com/grahamjenson/ger_rethinkdb_esm

**Comment by grahamjenson** [comment]
Hey,

So the rethinkdb esm has been extracted into its own package and project https://www.npmjs.com/package/ger_rethinkdb_esm . This is part of a larger effort to enable the implementation and use of esms that do not require changes to the core GER code.
