### ISSUE TITLE
RethinkDB ESM Performance

### ISSUE THREAD

**Issue by grahamjenson** [grahamjenson/ger#17]
Improve performance of RethinkDB ESM by adding indexes and moveing Node.js Logic to the database query.

bracng rethink_performance

**Comment by thelinuxlich** [comment]
I think we should close this issue, I've added many small optimizations and the difference between PG and RethinkDB adapters is not that absurd anymore.

**Comment by grahamjenson** [comment]
Awesome. I still have not got around to testing the rethinkdb esm with large (5gb+) datasets. Once you get that big, the areas we can focus on are highlighted. But for now, rethinkdb esm is much faster than before :)

**Comment by thelinuxlich** [comment]
Also note that single-server setup should be unfair for RethinkDB

**Comment by grahamjenson** [comment]
I think that RethinkDB should be more easily scalable than Postgres and could be the way which GER can be "Big Data" scalable. It is not so much about which is faster, just making sure that its performance is not correlated with the number of events.

For example, in the Postgres ESM I put a few `order by` statements in the wrong place and found that it tried to order ALL events, meaning the more events I put in made it unusably slow. It's performance was still fast at the smallish scale, and I couldn't find those issues till far too late.

**Comment by joshbedo** [comment]
How can you use the rethinkdb ESM?
