### ISSUE TITLE
API for avoiding the cold start problem

### ISSUE THREAD

**Issue by thelinuxlich** [grahamjenson/ger#42]
Something to bootstrap available things to act on

**Comment by grahamjenson** [comment]
the method `bootstrap` is meant to be a way to dump a lot of data quickly to bootstrap the database. However, I have had problems with this in the past, especially when getting to the GB's of data size. So now there is a method `events` which can dump lots of events quickly, but only in small batches. So the recommended way to use this is to have many processes dumping events in parallel to the events method.
