### ISSUE TITLE
What's the reason for setting the action weight on the fly during recommendation?

### ISSUE THREAD

**Issue by thelinuxlich** [grahamjenson/ger#43]
Just curious

**Comment by grahamjenson** [comment]
I think the less state GER has the easier it is to test, QA and use. For example, previously if you wanted to find the action weights that produced the best recommendations you would have had to change the actions weights state then call to generate recommendations, this would affect any live system running on the same data. Now you can alter the actions with each call making experimenting to find the best values much easier and not affecting any system running at the same time. 

Now, storing the actions, like default action values, is the responsibility of the system using GER.

P.S. sorry for the late reply :)

**Comment by mgreer** [comment]
I really like this feature: you can decide in the context where data is used what matters most, as opposed to the system deciding for you regardless of the content.
Am I looking for content I'd like to read? That people are sharing a lot of?
