### ISSUE TITLE
New feature: event weight decay

### ISSUE THREAD

**Issue by Superman132** [grahamjenson/ger#54]
It may be a good idea to decrease the value of an event as it gets closer to the expiry date, so that movies that Bob watched 3 months ago and movies he watched yesterday aren't valued the same in the system. I didn't have time to review the source code, but if is not there, this may be a good new feature.

**Comment by grahamjenson** [comment]
Hey, this feature already exists as the `event_decay_rate`, from the read me:

> `event_decay_rate` the rate at which event weight will decay over time, `weight * event_decay_rate ^ (- days since event)`

So an event of `weight = 1` that happened 10 days ago with an `event_decay_rate = 1.05` the calculation `1 * 1.05^-10` will result in an actual weight of about `0.61`.

**Comment by Superman132** [comment]
Oh okay thanks
